/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.ViewsNhanVien;

import DomainModels.CTSP;
import DomainModels.Loai;
import DomainModels.MauSac;
import DomainModels.NhaCungCap;
import DomainModels.SanPham;
import Servicies.IServiceSanPham;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Servicies.impl.ServiceSanPham;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

/**
 *
 * @author ADMIN
 */
public class FrameSanPhamNV extends javax.swing.JPanel {

    private IServiceSanPham ISerSP = new ServiceSanPham();
    private String urlAnh = "Icon/iconSanPham.png";

    /**
     * Creates new form FrameSanPhamNV
     */
    public FrameSanPhamNV() {
        initComponents();
        Icon iconClear = new ImageIcon("Icon/Edit.png");
        Icon iconThem = new ImageIcon("Icon/Add.png");
        Icon iconCapNhat = new ImageIcon("Icon/Up.png");
        Icon logoSanPham = new ImageIcon("Icon/iconSanPham.png");
        Icon iconCT = new ImageIcon("Icon/expand.png");

        this.btnLamTrongSP.setIcon(iconClear);
        this.btnThemSP.setIcon(iconThem);
        this.btnCapNhatSP.setIcon(iconCapNhat);
        this.btnLamTrongCTSP.setIcon(iconClear);
        this.btnThemCTSP.setIcon(iconThem);
        this.btnCapNhatCTSP.setIcon(iconCapNhat);
        this.lblLogoSanPham.setIcon(logoSanPham);
        this.btnCTLoai.setIcon(iconCT);
        this.btnCTMau.setIcon(iconCT);

//        reload();
        addTable(this.ISerSP.getListSP());
        addCboTenNCC(this.ISerSP.getListNCC());
        addCboLoai(this.ISerSP.getListLoai());
        addCboMauSac(this.ISerSP.getListMS());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        txtImport = new javax.swing.JButton();
        txtExport = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCapNhatSP = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdoCon = new javax.swing.JRadioButton();
        rdoHet = new javax.swing.JRadioButton();
        lblLogoSanPham = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnCapNhatCTSP = new javax.swing.JButton();
        btnThemCTSP = new javax.swing.JButton();
        btnLamTrongCTSP = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cboTenNCC = new javax.swing.JComboBox<>();
        btnCTLoai = new javax.swing.JButton();
        btnCTMau = new javax.swing.JButton();
        cboLoai = new javax.swing.JComboBox<>();
        cboMau = new javax.swing.JComboBox<>();
        txtMaCTSP = new javax.swing.JTextField();
        btnLamTrongSP = new javax.swing.JButton();
        btnThemSP = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1050, 690));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tìm kiếm sản phẩm");

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Trạng thái"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefesh.setText("Refresh");
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });

        txtImport.setText("Import Exel");
        txtImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImportActionPerformed(evt);
            }
        });

        txtExport.setText("Export Exel");
        txtExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExportActionPerformed(evt);
            }
        });

        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setText("Tìm theo mã");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnRefesh)
                        .addGap(18, 18, 18)
                        .addComponent(txtImport)
                        .addGap(18, 18, 18)
                        .addComponent(txtExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtImport)
                        .addComponent(txtExport))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnSearch)
                        .addComponent(btnRefesh)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Sản Phẩm");

        btnCapNhatSP.setText("Cập nhật");
        btnCapNhatSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatSPActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Mã sản phẩm");

        jLabel13.setText("Tên sản phẩm");

        jLabel3.setText("Trạng thái");

        rdoCon.setSelected(true);
        rdoCon.setText("Còn hàng");
        rdoCon.setEnabled(false);

        rdoHet.setText("Hết hàng");
        rdoHet.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addComponent(jLabel7)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(rdoCon)
                        .addGap(26, 26, 26)
                        .addComponent(rdoHet)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdoCon)
                    .addComponent(rdoHet))
                .addGap(34, 34, 34))
        );

        lblLogoSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoSanPhamMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Thông tin sản phẩm");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Chi tiết sản phẩm");

        btnCapNhatCTSP.setText("Cập nhật");
        btnCapNhatCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatCTSPActionPerformed(evt);
            }
        });

        btnThemCTSP.setText("Thêm");
        btnThemCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTSPActionPerformed(evt);
            }
        });

        btnLamTrongCTSP.setText("Làm trống");
        btnLamTrongCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamTrongCTSPActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Mã");

        jLabel15.setText("Loại");

        jLabel16.setText("Màu sắc");

        jLabel17.setText("Kích cỡ");

        jLabel18.setText("Số lượng");

        jLabel19.setText("Đơn giá");

        jLabel20.setText("Tên NCC");

        btnCTLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTLoaiActionPerformed(evt);
            }
        });

        btnCTMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTMauActionPerformed(evt);
            }
        });

        txtMaCTSP.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(txtSize)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCTLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCTMau, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cboTenNCC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMaCTSP)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCTLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCTMau, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel19))
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnLamTrongSP.setText("Làm trống");
        btnLamTrongSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamTrongSPActionPerformed(evt);
            }
        });

        btnThemSP.setText("Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel5)
                        .addContainerGap(513, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblLogoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLamTrongSP)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemSP)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhatSP)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLamTrongCTSP)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemCTSP)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhatCTSP))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamTrongCTSP)
                    .addComponent(btnThemCTSP)
                    .addComponent(btnCapNhatCTSP)
                    .addComponent(btnThemSP)
                    .addComponent(btnCapNhatSP)
                    .addComponent(btnLamTrongSP))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        int i = 0;
        for (SanPham sp : this.ISerSP.getListSP()) {
            i++;
            model.addRow(new Object[]{i, sp.getMa(), sp.getTen(), sp.getTrangThai()});
        }
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int row = this.tblSanPham.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để hiển thị!");
            return;
        }
        String ma = this.tblSanPham.getValueAt(row, 1).toString();
        String ten = this.tblSanPham.getValueAt(row, 2).toString();
        String trangThai = this.tblSanPham.getValueAt(row, 3).toString();

        txtMa.setText(ma);
        txtTen.setText(ten);
        if (trangThai.equals("Còn hàng")) {
            rdoCon.setSelected(true);
        } else {
            rdoHet.setSelected(true);
        }
//        txtMa.setSelectedItem(ma);

        ArrayList<CTSP> list = this.ISerSP.getListCTSP(ma);
        if (list.size() == 0) {
            this.txtMaCTSP.setText("");
            this.cboTenNCC.setSelectedIndex(0);
            this.txtDonGia.setText("");
            this.cboLoai.setSelectedIndex(0);
            this.cboMau.setSelectedIndex(0);
            this.txtSize.setText("");
            this.txtSoLuong.setText("");
            Icon icon = new ImageIcon("Icon/iconSanPham.png");
            this.lblLogoSanPham.setIcon(icon);
        } else {
            for (CTSP a : list) {
                this.txtMaCTSP.setText(a.getMa());
                this.cboLoai.setSelectedItem(a.getLoai());
                this.txtDonGia.setText(a.getGiaBan() + "");
                this.cboMau.setSelectedItem(a.getMau());
                this.txtSize.setText(a.getKichCo() + "");
                this.txtSoLuong.setText(a.getSoLuong() + "");
                this.cboTenNCC.setSelectedItem(a.getNhaCC());
                Icon icon = new ImageIcon(a.getUrlAnh());
                this.lblLogoSanPham.setIcon(icon);
            }
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String ma = this.txtSearch.getText();
        if (ma.length() == 0 || ma.equals("Tìm theo mã")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền thông tin!");
            this.txtSearch.requestFocus();
            return;
        }
        List<SanPham> listSP = this.ISerSP.checkMa(ma);
        if (listSP.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không có sản phẩm bạn cần tìm!");
            this.txtMa.setText("");
            this.txtTen.setText("");
            this.rdoCon.setSelected(true);

            this.txtMaCTSP.setText("");
            this.cboTenNCC.setSelectedIndex(0);
            this.txtDonGia.setText("");
            this.cboLoai.setSelectedIndex(0);
            this.cboMau.setSelectedIndex(0);
            this.txtSize.setText("");
            this.txtSoLuong.setText("");
            Icon icon = new ImageIcon("Icon/iconSanPham.png");
            this.lblLogoSanPham.setIcon(icon);
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!");
            for (SanPham sp : listSP) {
                DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
                model.setRowCount(0);
                model.addRow(new Object[]{1, sp.getMa(), sp.getTen(), sp.getTrangThai() == 0 ? "Còn hàng" : "Hết hàng"});
                this.txtMa.setText(sp.getMa());
                this.txtTen.setText(sp.getTen());
                if (sp.getTrangThai() == 0) {
                    this.rdoCon.setSelected(true);
                } else {
                    this.rdoHet.setSelected(true);
                }

            }

            List<CTSP> list = this.ISerSP.getListCTSP(ma);
            if (list.size() == 0) {
                this.txtMaCTSP.setText("");
                this.cboTenNCC.setSelectedIndex(0);
                this.txtDonGia.setText("");
                this.cboLoai.setSelectedIndex(0);
                this.cboMau.setSelectedIndex(0);
                this.txtSize.setText("");
                this.txtSoLuong.setText("");
                Icon icon = new ImageIcon("Icon/iconSanPham.png");
                this.lblLogoSanPham.setIcon(icon);
            } else {
                for (CTSP a : list) {

                    this.tblSanPham.setRowSelectionInterval(0, 0);
                    this.txtMaCTSP.setText(a.getMa());
                    this.cboLoai.setSelectedItem(a.getLoai());
                    this.txtDonGia.setText(a.getGiaBan() + "");
                    this.cboMau.setSelectedItem(a.getMau());
                    this.txtSize.setText(a.getKichCo() + "");
                    this.txtSoLuong.setText(a.getSoLuong() + "");
                    this.cboTenNCC.setSelectedItem(a.getNhaCC());
                    Icon icon = new ImageIcon(a.getUrlAnh());
                    this.lblLogoSanPham.setIcon(icon);
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCapNhatSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatSPActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_btnCapNhatSPActionPerformed

    private void lblLogoSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoSanPhamMouseClicked
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_lblLogoSanPhamMouseClicked

    private void btnCapNhatCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatCTSPActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_btnCapNhatCTSPActionPerformed

    private void btnThemCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTSPActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;

    }//GEN-LAST:event_btnThemCTSPActionPerformed

    private void btnLamTrongCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamTrongCTSPActionPerformed

        this.txtMaCTSP.setText("");
        this.cboTenNCC.setSelectedIndex(0);
        this.cboLoai.setSelectedIndex(0);
        this.cboMau.setSelectedIndex(0);
        this.txtDonGia.setText("");
        this.txtSize.setText("");
        this.txtSoLuong.setText("");
        //        reload();
    }//GEN-LAST:event_btnLamTrongCTSPActionPerformed

    private void btnCTLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTLoaiActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_btnCTLoaiActionPerformed

    private void btnCTMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTMauActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_btnCTMauActionPerformed

    private void btnLamTrongSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamTrongSPActionPerformed
        this.txtMa.setText("");
        this.txtTen.setText("");
        this.rdoCon.setSelected(true);
    }//GEN-LAST:event_btnLamTrongSPActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void txtImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_txtImportActionPerformed

    private void txtExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExportActionPerformed
        JOptionPane.showMessageDialog(this, "Phải đăng nhập quyền quản lý!");
        return;
    }//GEN-LAST:event_txtExportActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        this.txtSearch.setText("");
        this.txtSearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTLoai;
    private javax.swing.JButton btnCTMau;
    private javax.swing.JButton btnCapNhatCTSP;
    private javax.swing.JButton btnCapNhatSP;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLamTrongCTSP;
    private javax.swing.JButton btnLamTrongSP;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThemCTSP;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboTenNCC;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogoSanPham;
    private javax.swing.JRadioButton rdoCon;
    private javax.swing.JRadioButton rdoHet;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JButton txtExport;
    private javax.swing.JButton txtImport;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaCTSP;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    private void addTable(List<SanPham> listSP) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        int i = 0;
        for (SanPham sp : this.ISerSP.getListSP()) {
            i++;
            model.addRow(new Object[]{i, sp.getMa(), sp.getTen(), sp.getTrangThai()});
        }
    }

    private void addCboTenNCC(ArrayList<NhaCungCap> list) {
        DefaultComboBoxModel modelMa = (DefaultComboBoxModel) cboTenNCC.getModel();

        for (NhaCungCap sp : list) {
            modelMa.addElement(sp.getTen());
        }
    }

    private void addCboLoai(List<Loai> listLoai) {
        DefaultComboBoxModel modelMa = (DefaultComboBoxModel) cboLoai.getModel();

        for (Loai loai : listLoai) {
            modelMa.addElement(loai.getTen());
        }
    }

    private void addCboMauSac(List<MauSac> listMS) {
        DefaultComboBoxModel modelMa = (DefaultComboBoxModel) cboMau.getModel();

        for (MauSac ms : listMS) {
            modelMa.addElement(ms.getTen());
        }
    }
}
